const SESSION_ENV_KEYS = [
  'SLACK_AGENT_ACTIVE_CONTEXT_TTL_HOURS',
  'SLACK_AGENT_ACTIVE_CONTEXT_TTL_DAYS',
  'SLACK_AGENT_WAITING_CLARIFICATION_TTL_DAYS',
  'SLACK_AGENT_RECENT_SESSION_DAYS',
  'SLACK_AGENT_ARCHIVE_AFTER_DAYS',
  'SLACK_AGENT_TURN_TIMEOUT_SECONDS',
  'SLACK_AGENT_SESSION_LEASE_SECONDS',
  'SLACK_AGENT_PROVIDER_THREAD_TTL_HOURS',
  'CODING_AGENT_RUN_TIMEOUT_MINUTES',
];

const GATEWAY_ENV_KEYS = [
  'NODE_ENV',
  'INTERNAL_CALLBACK_TOKEN',
  'INTERNAL_CALLBACK_TOKEN_REQUIRED',
  'PAGES_GATEWAY_API_TOKEN',
  'PAGES_INTERNAL_API_TOKEN',
  'PAGES_GATEWAY_API_TOKEN_REQUIRED',
  'SLACK_SIGNING_SECRET',
  'SLACK_SIGNATURE_REQUIRED',
  'SLACK_EVENTS_PROCESSING_MODE',
  'SLACK_REACTION_ON_RECEIVE',
  'SLACK_WORKING_REACTION',
  'SLACK_DONE_REACTION',
  'SLACK_FAILED_REACTION',
  'SLACK_AGENT_TURN_URL',
  'SLACK_AGENT_ANALYZE_URL',
  'SLACK_AGENT_SHARED_SECRET',
  'SLACK_AGENT_MERGE_SUMMARY_URL',
  'SLACK_NOTIFIER_URL',
  'SLACK_NOTIFIER_SHARED_SECRET',
  'PAGES_SLACK_NOTIFIER_URL',
  'PAGES_SLACK_NOTIFIER_SHARED_SECRET',
  'GITHUB_REPO',
  'GITHUB_ENTERPRISE_API_BASE_URL',
  'GITHUB_API_BASE_URL',
  'GITHUB_STATUS_TOKEN',
  'GITHUB_APP_ID',
  'GITHUB_APP_INSTALLATION_ID',
  'GITHUB_APP_PRIVATE_KEY',
  'GITHUB_APP_PRIVATE_KEY_B64',
  'GITHUB_APP_INSTALLATION_TOKEN',
  'GITHUB_TOKEN',
  'GITHUB_WEBHOOK_SECRET',
  'GITHUB_REVIEW_AGENT_ALLOWLIST',
  'GITHUB_REVIEW_AGENT_LOGINS',
  'GITHUB_REVIEW_AGENT_TIMEOUT_SECONDS',
  'GITHUB_SITE_CHECK_NAMES',
  'GITHUB_SITE_CHECK_APP_LOGINS',
  'GITHUB_PLATFORM_CI_CHECK_NAMES',
  'GITHUB_PLATFORM_CI_APP_LOGINS',
  'MERGE_ANNOUNCEMENT_ENABLED',
  'MERGE_ANNOUNCEMENT_CHANNEL_ID',
  'MERGE_ANNOUNCEMENT_BASE_REFS',
  'MERGE_ANNOUNCEMENT_AGENT_ENABLED',
  'MERGE_ANNOUNCEMENT_INCLUDE_SITE_PRS',
  'MERGE_ANNOUNCEMENT_MENTION_USER_IDS',
  'PAGES_WORKER_START_URL',
  'PAGES_WORKER_SHARED_SECRET',
];

function sessionEnv(source = process.env) {
  return Object.fromEntries(SESSION_ENV_KEYS.map((key) => [key, source[key]]).filter(([, value]) => value));
}

export function buildGatewayEnv(source = process.env) {
  return {
    ...sessionEnv(source),
    ...Object.fromEntries(GATEWAY_ENV_KEYS.map((key) => [key, source[key]])),
  };
}
