export function buildOpenApi(config) {
  return {
    openapi: '3.1.0',
    info: {
      title: 'XD Pages API',
      version: '2.0.0',
      description: 'Control plane API for XD Pages.',
    },
    servers: [{ url: config.apiBaseUrl }],
    security: [{ bearerAuth: [] }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'CLI token or access key',
        },
      },
      schemas: {
        ErrorResponse: {
          type: 'object',
          required: ['error'],
          properties: {
            error: {
              type: 'object',
              required: ['code', 'message'],
              properties: {
                code: { type: 'string' },
                message: { type: 'string' },
                action: { type: 'string' },
              },
            },
          },
        },
        CliManagedDeploymentRequest: {
          type: 'object',
          description:
            'Deployment upload payload generated by the XD Pages CLI. Use `pages deploy <source> <site>` or ' +
            '`pages deploy --dry-run --json`; do not construct this payload by hand.',
          additionalProperties: true,
        },
        DeploymentDecision: {
          type: 'object',
          required: ['deploymentShape', 'requestedFallback', 'resolvedFallback', 'routingMode'],
          properties: {
            deploymentShape: {
              type: 'string',
              enum: ['assets-only', 'worker-only', 'worker-with-assets'],
              description: 'Resolved platform execution shape. Returned for explanation; not a user input field.',
            },
            requestedFallback: { type: 'string', enum: ['auto', 'index', 'not-found'] },
            resolvedFallback: { type: ['string', 'null'], enum: ['index', 'not-found', null] },
            routingMode: {
              type: 'string',
              enum: ['assets-only', 'worker-only', 'worker-first'],
            },
          },
        },
        RollbackRequest: {
          type: 'object',
          properties: {
            siteId: {
              type: 'string',
              description: 'Optional guardrail. If provided, the target version must belong to this site id.',
            },
            siteSlug: {
              type: 'string',
              description: 'Optional guardrail. If provided, the target version must belong to this site slug.',
            },
          },
        },
        SiteVisibility: {
          type: 'string',
          enum: ['internal', 'org', 'acl', 'owner', 'disabled'],
          description:
            'First release is protected by the router IP allowlist for every visibility. ' +
            'public is reserved for a future exposure model.',
        },
        SiteUpdateRequest: {
          type: 'object',
          required: ['visibility'],
          properties: {
            visibility: { $ref: '#/components/schemas/SiteVisibility' },
          },
        },
        SiteAclEntry: {
          type: 'object',
          required: ['subjectType', 'subjectValue'],
          properties: {
            subjectType: {
              type: 'string',
              enum: ['email', 'department'],
              description:
                'People are specified by email. Departments are specified by full department path and include subdepartments. ' +
                'Internal SSO user ids, account ids, employee numbers, and group subjects are not accepted as public ' +
                'ACL subjects.',
            },
            subjectValue: { type: 'string' },
            effect: {
              type: 'string',
              enum: ['allow'],
              default: 'allow',
              description: 'deny is not supported in the first release.',
            },
            accessRole: {
              type: 'string',
              enum: ['viewer'],
              default: 'viewer',
            },
          },
        },
        SiteAclReplaceRequest: {
          type: 'object',
          required: ['entries'],
          properties: {
            entries: {
              type: 'array',
              maxItems: 200,
              items: { $ref: '#/components/schemas/SiteAclEntry' },
            },
          },
        },
      },
    },
    paths: {
      '/.xd-pages/api/sites': {
        get: {
          summary: 'List sites visible to the authenticated actor; access keys require read:site',
          responses: {
            200: { description: 'Sites returned' },
            403: { description: 'Access key missing read:site scope' },
            401: { description: 'Authentication required' },
          },
        },
        post: {
          summary: 'Create a site',
          responses: {
            201: { description: 'Site created' },
            409: { description: 'Site slug conflict' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}': {
        get: {
          summary: 'Get a site; access keys require read:site',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Site returned' },
            403: { description: 'Access key missing read:site scope' },
            404: { description: 'Site not found' },
          },
        },
        patch: {
          summary: 'Update site visibility and invalidate existing site sessions by policyVersion',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteUpdateRequest' },
              },
            },
          },
          'x-error-codes': ['SITE_VISIBILITY_INVALID', 'SITE_POLICY_FORBIDDEN', 'ROUTE_SNAPSHOT_WRITE_FAILED'],
          responses: {
            200: { description: 'Site policy updated' },
            400: { description: 'Invalid visibility' },
            403: { description: 'Only the site owner can manage site policy' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/acl': {
        get: {
          summary: 'List site ACL entries',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'ACL entries returned' },
            404: { description: 'Site not found' },
          },
        },
        put: {
          summary: 'Replace site ACL entries using allow-only OR semantics',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries replaced' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Only the site owner can manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/acl/entries': {
        post: {
          summary: 'Grant additional site ACL entries using allow-only OR semantics',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries granted' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Only the site owner can manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
        delete: {
          summary: 'Revoke site ACL entries incrementally',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries revoked' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Only the site owner can manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/access-keys': {
        get: {
          summary: 'List access keys',
          responses: {
            200: { description: 'Access keys returned without plaintext or hash' },
          },
        },
        post: {
          summary: 'Create a site-scoped access key',
          responses: {
            201: { description: 'Access key created; plaintext returned once' },
          },
        },
      },
      '/.xd-pages/api/access-keys/{id}': {
        delete: {
          summary: 'Revoke an access key',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Access key revoked' },
            404: { description: 'Access key not found' },
          },
        },
      },
      '/.xd-pages/api/auth/whoami': {
        get: {
          summary: 'Return the authenticated actor for CLI token or access key validation',
          responses: {
            200: { description: 'Authenticated actor returned without token plaintext or hashes' },
            401: { description: 'Authentication required or invalid' },
            403: { description: 'Authenticated user is not active' },
          },
        },
      },
      '/.xd-pages/api/deployments': {
        post: {
          summary: 'Create a deployment from a CLI-managed upload payload',
          parameters: [{ name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'multipart/form-data': {
                schema: { $ref: '#/components/schemas/CliManagedDeploymentRequest' },
              },
            },
          },
          'x-error-codes': [
            'ASSET_MANIFEST_INVALID',
            'ASSET_FILES_REQUIRED',
            'CLI_UPLOAD_PROTOCOL_REQUIRED',
            'CONTENT_HASH_MISMATCH',
            'PUBLISH_PLAN_INVALID',
            'PUBLISH_PLAN_VERSION_UNSUPPORTED',
            'FALLBACK_REQUIRES_ASSETS',
            'INVALID_MULTIPART',
            'PAYLOAD_TOO_LARGE',
            'DEPLOYMENT_PLATFORM_CONFIG_INVALID',
            'DEPLOYMENT_UPLOAD_FAILED',
            'DEPLOYMENT_VERIFY_FAILED',
            'DEPLOYMENT_STATE_WRITE_FAILED',
            'DEPLOYMENT_CAPACITY_EXHAUSTED',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'IDEMPOTENCY_CONFLICT',
          ],
          responses: {
            201: { description: 'Deployment created' },
            400: { description: 'Invalid deployment request' },
            413: { description: 'Deployment payload too large for the current upload path' },
            500: { description: 'Deployment platform configuration invalid' },
            502: { description: 'Deployment upload or verification failed' },
            503: { description: 'Deployment capacity exhausted or route snapshot write failed' },
            409: { description: 'Idempotency conflict' },
          },
        },
      },
      '/.xd-pages/api/deployments/{id}': {
        get: {
          summary: 'Get deployment status; access keys require read:site',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Deployment returned' },
            403: { description: 'Access key missing read:site scope' },
            404: { description: 'Deployment not found' },
          },
        },
      },
      '/.xd-pages/api/versions/{id}/rollback': {
        post: {
          summary: 'Rollback a site route to a previous immutable version',
          parameters: [
            { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string' } },
          ],
          requestBody: {
            required: false,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/RollbackRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SITE_NOT_FOUND',
            'VERSION_NOT_FOUND',
            'ROLLBACK_FORBIDDEN',
            'ROLLBACK_SITE_MISMATCH',
            'ROLLBACK_VERSION_UNAVAILABLE',
            'ROUTE_ACTIVATION_CONFLICT',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'IDEMPOTENCY_CONFLICT',
          ],
          responses: {
            201: { description: 'Rollback deployment created' },
            409: { description: 'Idempotency conflict' },
          },
        },
      },
    },
  };
}
