export function buildOpenApi(config) {
  return {
    openapi: '3.1.0',
    info: {
      title: 'XD Cell API',
      version: '2.0.0',
      description: 'Control plane API for XD Cell.',
    },
    servers: [{ url: config.apiBaseUrl }],
    security: [{ bearerAuth: [] }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'Access key or Cindy connection assertion (JWT)',
          description:
            'Management APIs accept an XD Cell access key, or a short-lived Cindy connection assertion ' +
            '(RS256 JWT with typ=connection) verified per request against the trusted Cindy JWKS. ' +
            'Connection assertions carry the deploy:site, read:site, and rollback:site scopes and cannot manage access keys.',
        },
      },
      headers: {
        DeploymentTraceId: {
          description: 'Server-generated deployment trace id for correlating API, D1, Provider, and Console diagnostics.',
          schema: { type: 'string', pattern: '^dtr_[A-Za-z0-9_-]{1,128}$' },
        },
      },
      schemas: {
        ErrorResponse: {
          type: 'object',
          required: ['error'],
          properties: {
            error: {
              type: 'object',
              required: ['code', 'message'],
              properties: {
                code: { type: 'string' },
                message: { type: 'string' },
                action: { type: 'string' },
              },
            },
          },
        },
        CliManagedDeploymentRequest: {
          type: 'object',
          description:
            'Deployment upload payload generated by the XD Cell CLI. Use `xd-cell deploy <entry> <site>` or ' +
            '`xd-cell deploy --dry-run --json`; do not construct this payload by hand. CLI may include teamId ' +
            'when deploying as a team publisher.',
          properties: {
            metadata: {
              type: 'string',
              contentMediaType: 'application/json',
              contentSchema: { $ref: '#/components/schemas/DeploymentMetadata' },
              description:
                'JSON metadata part. Controlled integrations may include optional title: omit it to leave an existing ' +
                'site title unchanged, send a string to set the normalized display name, or send null to clear it. ' +
                'The current xd-cell CLI does not send title. For team deploys the metadata carries teamId; the API ' +
                'validates team publisher role.',
            },
          },
          additionalProperties: true,
        },
        DeploymentMetadata: {
          type: 'object',
          properties: {
            title: {
              type: ['string', 'null'],
              description:
                'Optional site display name. Omit it to preserve the current title, send a string to update it, ' +
                'or send null to clear it.',
            },
          },
          additionalProperties: true,
        },
        WhoamiResponse: {
          type: 'object',
          required: ['environment', 'actor'],
          properties: {
            environment: { type: 'string', enum: ['production', 'staging'] },
            actor: { $ref: '#/components/schemas/WhoamiActor' },
          },
        },
        WhoamiActor: {
          oneOf: [
            {
              type: 'object',
              required: ['type', 'credentialType', 'userId', 'email', 'name', 'scopes'],
              properties: {
                type: { type: 'string', const: 'user' },
                credentialType: { type: 'string', const: 'access_key' },
                userId: { type: 'string' },
                email: { type: 'string', format: 'email' },
                name: { type: ['string', 'null'] },
                scopes: { type: 'array', items: { type: 'string' } },
              },
              additionalProperties: false,
            },
            {
              type: 'object',
              required: [
                'type',
                'credentialType',
                'accessKeyId',
                'userId',
                'email',
                'name',
                'ownerType',
                'ownerId',
                'siteId',
                'scopes',
              ],
              properties: {
                type: { type: 'string', const: 'access_key' },
                credentialType: { type: 'string', const: 'access_key' },
                accessKeyId: { type: 'string' },
                userId: { type: ['string', 'null'], description: 'Creating user for team access keys, owner user otherwise.' },
                email: { type: ['string', 'null'], format: 'email' },
                name: { type: ['string', 'null'] },
                ownerType: { type: 'string', enum: ['user', 'team'] },
                ownerId: { type: 'string' },
                siteId: { type: ['string', 'null'] },
                scopes: { type: 'array', items: { type: 'string' } },
              },
              additionalProperties: false,
            },
          ],
        },
        Team: {
          type: 'object',
          required: ['id', 'name', 'teamType', 'status', 'currentUserRole'],
          properties: {
            id: { type: 'string', description: 'Team id used by `xd-cell deploy --team <teamId>`.' },
            name: { type: 'string' },
            description: { type: ['string', 'null'] },
            teamType: { type: 'string', enum: ['custom', 'department'] },
            departmentPath: { type: ['string', 'null'] },
            status: { type: 'string' },
            currentUserRole: { type: ['string', 'null'], enum: ['viewer', 'publisher', 'admin', null] },
            currentUserMembershipSource: { type: ['string', 'null'] },
            siteCount: { type: 'integer', minimum: 0 },
            memberCount: { type: 'integer', minimum: 0 },
            createdAt: { type: 'string' },
            updatedAt: { type: 'string' },
          },
          additionalProperties: false,
        },
        TeamsResponse: {
          type: 'object',
          required: ['environment', 'teams'],
          properties: {
            environment: { type: 'string', enum: ['production', 'staging'] },
            teams: { type: 'array', items: { $ref: '#/components/schemas/Team' } },
          },
        },
        DeploymentDecision: {
          type: 'object',
          required: ['deploymentShape', 'requestedFallback', 'resolvedFallback', 'routingMode'],
          properties: {
            deploymentShape: {
              type: 'string',
              enum: ['assets-only', 'worker-only', 'worker-with-assets'],
              description: 'Resolved platform execution shape. Returned for explanation; not a user input field.',
            },
            requestedFallback: {
              type: 'string',
              enum: ['auto', 'index', 'not-found', 'none', 'single-page-application', '404-page'],
            },
            resolvedFallback: { type: ['string', 'null'], enum: ['index', 'not-found', 'none', null] },
            routingMode: {
              type: 'string',
              enum: ['assets-only', 'worker-only', 'worker-first'],
            },
          },
        },
        RollbackRequest: {
          type: 'object',
          properties: {
            siteId: {
              type: 'string',
              description: 'Optional guardrail. If provided, the target version must belong to this site id.',
            },
            siteSlug: {
              type: 'string',
              description: 'Optional guardrail. If provided, the target version must belong to this site slug.',
            },
          },
        },
        SiteVisibility: {
          type: 'string',
          enum: ['internal', 'org', 'acl', 'owner', 'disabled'],
          description:
            'Legacy visibility is the identity access mode: internal means anonymous access, while org, acl, owner, ' +
            'and disabled keep their existing semantics. Network reachability is controlled separately by the Admin-only ' +
            'exposure policy; exposure is not a user visibility value.',
        },
        SiteUpdateRequest: {
          type: 'object',
          required: ['visibility'],
          properties: {
            visibility: { $ref: '#/components/schemas/SiteVisibility' },
          },
        },
        SiteMetadataUpdateRequest: {
          type: 'object',
          additionalProperties: false,
          anyOf: [{ required: ['title'] }, { required: ['slug'] }],
          properties: {
            title: {
              type: ['string', 'null'],
              pattern: '\\S',
              description:
                'Optional display name. String values are NFC-normalized; control characters and U+2028/U+2029 are rejected, ' +
                'then surrounding whitespace is trimmed and the result must contain 1-80 Unicode code points. ' +
                'Send null to clear it.',
            },
            slug: {
              type: 'string',
              description:
                'Canonical site URL slug. Input is trimmed and lowercased before validation; the normalized slug must contain ' +
                '2-50 lowercase ASCII letters, digits, or hyphens, start and end with an alphanumeric character, and not be ' +
                'reserved. The previous URL stops resolving and is released after a safety hold.',
            },
          },
        },
        SiteMetadataProjection: {
          type: 'object',
          required: ['id', 'title', 'displayName', 'slug', 'routingStatus', 'url'],
          properties: {
            id: { type: 'string' },
            title: { type: ['string', 'null'] },
            displayName: { type: 'string' },
            slug: { type: 'string' },
            routingStatus: { type: 'string', enum: ['ready', 'pending'] },
            url: { type: ['string', 'null'], format: 'uri' },
          },
          additionalProperties: false,
        },
        PublicSiteOwner: {
          type: 'object',
          required: ['type'],
          properties: {
            type: { type: 'string', enum: ['user', 'team'] },
          },
          additionalProperties: false,
        },
        PublicSite: {
          type: 'object',
          required: [
            'id',
            'title',
            'displayName',
            'slug',
            'environment',
            'routingStatus',
            'hostname',
            'url',
            'owner',
            'visibility',
            'createdAt',
            'updatedAt',
          ],
          properties: {
            id: { type: 'string' },
            title: { type: ['string', 'null'] },
            displayName: { type: 'string' },
            slug: { type: 'string' },
            environment: { type: 'string', enum: ['production', 'staging', 'local'] },
            routingStatus: { type: 'string', enum: ['ready', 'pending'] },
            hostname: { type: 'string' },
            url: { type: 'string', format: 'uri' },
            owner: { $ref: '#/components/schemas/PublicSiteOwner' },
            visibility: { type: 'string', enum: ['internal', 'org', 'acl', 'owner'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          additionalProperties: false,
        },
        PublicSitesPagination: {
          type: 'object',
          required: ['nextCursor'],
          properties: {
            nextCursor: { type: ['string', 'null'], maxLength: 2048 },
          },
          additionalProperties: false,
        },
        PublicSitesResponse: {
          type: 'object',
          required: ['sites', 'pagination'],
          properties: {
            sites: { type: 'array', items: { $ref: '#/components/schemas/PublicSite' } },
            pagination: { $ref: '#/components/schemas/PublicSitesPagination' },
          },
          additionalProperties: false,
        },
        SiteMetadataUpdateResponse: {
          type: 'object',
          required: ['site'],
          properties: {
            site: { $ref: '#/components/schemas/SiteMetadataProjection' },
          },
        },
        SiteMetadataPendingResponse: {
          type: 'object',
          required: ['site', 'warning'],
          properties: {
            site: { $ref: '#/components/schemas/SiteMetadataProjection' },
            warning: {
              type: 'object',
              required: ['code', 'message', 'action'],
              properties: {
                code: { type: 'string', const: 'SITE_METADATA_ROUTING_PENDING' },
                message: { type: 'string' },
                action: { type: 'string' },
              },
            },
          },
        },
        AdminSiteExposureRequest: {
          type: 'object',
          required: ['exposure'],
          additionalProperties: false,
          properties: {
            exposure: {
              type: 'string',
              enum: ['internal', 'public'],
              description: 'Platform-admin network exposure. This field is not accepted by ordinary site policy APIs.',
            },
            reason: {
              type: 'string',
              maxLength: 500,
              description: 'Required when enabling public exposure; optional when disabling it.',
            },
          },
        },
        AdminSiteExposureReason: {
          type: 'object',
          required: ['text', 'changedAt'],
          properties: {
            text: { type: 'string', maxLength: 500 },
            changedAt: { type: 'string', format: 'date-time' },
          },
        },
        AdminSiteAccess: {
          type: 'object',
          required: ['exposure', 'accessMode', 'visibility', 'aclEntries', 'exposureReason'],
          properties: {
            exposure: { type: 'string', enum: ['internal', 'public'] },
            accessMode: { type: 'string', enum: ['anonymous', 'org', 'acl', 'owner', 'disabled'] },
            visibility: { $ref: '#/components/schemas/SiteVisibility' },
            aclEntries: {
              type: 'array',
              items: { $ref: '#/components/schemas/SiteAclEntry' },
            },
            exposureReason: {
              oneOf: [{ $ref: '#/components/schemas/AdminSiteExposureReason' }, { type: 'null' }],
            },
          },
        },
        AdminSiteAccessResponse: {
          type: 'object',
          required: ['access'],
          properties: {
            access: { $ref: '#/components/schemas/AdminSiteAccess' },
          },
        },
        AdminSiteExposureUpdateResponse: {
          type: 'object',
          required: ['access', 'auditStatus'],
          properties: {
            access: { $ref: '#/components/schemas/AdminSiteAccess' },
            auditStatus: { type: 'string', enum: ['confirmed', 'unconfirmed'] },
          },
        },
        SiteTransferRequest: {
          type: 'object',
          required: ['ownerType'],
          properties: {
            ownerType: {
              type: 'string',
              enum: ['user', 'team'],
              description:
                'Target owner type. Team access tokens cannot change site ownership, including transfers to personal owners.',
            },
            ownerId: {
              type: 'string',
              description:
                'Target user id for ownerType=user or team id for ownerType=team. Personal transfers are limited to self.',
            },
            teamId: {
              type: 'string',
              description: 'Target team id. Equivalent to ownerId when ownerType=team.',
            },
          },
        },
        SiteAclEntry: {
          type: 'object',
          required: ['subjectType', 'subjectValue'],
          properties: {
            subjectType: {
              type: 'string',
              enum: ['email', 'department'],
              description:
                'People are specified by email. Departments are specified by full department path and include subdepartments. ' +
                'Internal SSO user ids, account ids, employee numbers, and group subjects are not accepted as public ' +
                'ACL subjects.',
            },
            subjectValue: { type: 'string' },
            effect: {
              type: 'string',
              enum: ['allow'],
              default: 'allow',
              description: 'deny is not supported in the first release.',
            },
            accessRole: {
              type: 'string',
              enum: ['viewer'],
              default: 'viewer',
            },
          },
        },
        SiteAclReplaceRequest: {
          type: 'object',
          required: ['entries'],
          properties: {
            entries: {
              type: 'array',
              maxItems: 200,
              items: { $ref: '#/components/schemas/SiteAclEntry' },
            },
          },
        },
        SiteSecretPutRequest: {
          type: 'object',
          required: ['name', 'value'],
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              description: 'Worker binding name. Secret value is never returned by the API.',
            },
            value: {
              type: 'string',
              minLength: 1,
              description: 'Secret value. Do not log or persist this outside the secret store.',
            },
          },
        },
        SiteSecretDeleteRequest: {
          type: 'object',
          required: ['name'],
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              description: 'Worker binding name to disable for future deployments.',
            },
          },
        },
        SiteSecretMetadata: {
          type: 'object',
          required: ['name', 'revision', 'updatedAt'],
          additionalProperties: false,
          properties: {
            name: { type: 'string', description: 'Worker secret binding name. The secret value is never returned.' },
            revision: { type: 'integer', minimum: 1 },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        SiteSecretsResponse: {
          type: 'object',
          required: ['secrets'],
          additionalProperties: false,
          properties: {
            secrets: {
              type: 'array',
              items: { $ref: '#/components/schemas/SiteSecretMetadata' },
            },
          },
        },
        SiteVarPutRequest: {
          type: 'object',
          required: ['name', 'value'],
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              description: 'Non-sensitive Worker plain-text binding name.',
            },
            value: {
              type: 'string',
              description:
                'Non-sensitive plain-text value. Returned by the authorized GET operation but omitted from mutation responses.',
            },
          },
        },
        SiteVarDeleteRequest: {
          type: 'object',
          required: ['name'],
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              description: 'Non-sensitive Worker plain-text binding name to delete.',
            },
          },
        },
        SiteRuntimeVar: {
          type: 'object',
          required: ['name', 'value', 'revision', 'updatedAt'],
          additionalProperties: false,
          properties: {
            name: { type: 'string', description: 'Non-sensitive Worker plain-text binding name.' },
            value: { type: 'string', description: 'Non-sensitive Worker plain-text binding value.' },
            revision: { type: 'integer', minimum: 1 },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        SiteVarsResponse: {
          type: 'object',
          required: ['vars'],
          additionalProperties: false,
          properties: {
            vars: {
              type: 'array',
              items: { $ref: '#/components/schemas/SiteRuntimeVar' },
            },
          },
        },
        AdminUser: {
          type: 'object',
          required: ['id', 'email', 'employeeStatus', 'isPlatformAdmin'],
          properties: {
            id: { type: 'string' },
            email: { type: 'string', format: 'email' },
            realname: { type: ['string', 'null'] },
            employeeStatus: { type: 'string' },
            departmentPath: { type: ['string', 'null'] },
            isPlatformAdmin: { type: 'boolean' },
            lastLoginAt: { type: ['string', 'null'] },
            createdAt: { type: 'string' },
            updatedAt: { type: 'string' },
          },
          additionalProperties: false,
        },
        AdminUsersResponse: {
          type: 'object',
          required: ['users', 'pagination'],
          properties: {
            users: { type: 'array', items: { $ref: '#/components/schemas/AdminUser' } },
            pagination: {
              type: 'object',
              required: ['total', 'limit', 'offset'],
              properties: {
                total: { type: 'integer', minimum: 0 },
                limit: { type: 'integer', minimum: 1, maximum: 100 },
                offset: { type: 'integer', minimum: 0 },
              },
              additionalProperties: false,
            },
          },
          additionalProperties: false,
        },
      },
    },
    paths: {
      '/.xd-pages/api/public/sites': {
        get: {
          summary: 'List active sites discoverable by the authenticated user',
          description:
            'Authenticated Public Sites directory for the current API Worker environment; public names this API lane ' +
            'and does not mean anonymous access or exposure=public. Cindy connection assertions, CLI login credentials, ' +
            'and unscoped personal access keys with read:site or * may use it. Deploy-only, team-owned, and site-scoped ' +
            'keys are forbidden. Repeated or unknown query parameters return 400.',
          parameters: [
            {
              name: 'limit',
              in: 'query',
              required: false,
              schema: { type: 'integer', minimum: 1, maximum: 100, default: 50 },
              description: 'Maximum number of sites to return.',
            },
            {
              name: 'cursor',
              in: 'query',
              required: false,
              schema: {
                type: 'string',
                minLength: 1,
                maxLength: 2048,
                pattern: '^[A-Za-z0-9_-]+$',
              },
              description: 'Opaque base64url cursor returned by this endpoint.',
            },
          ],
          'x-error-codes': [
            'LEGACY_TOKEN_UNSUPPORTED',
            'PUBLIC_SITES_QUERY_INVALID',
            'PAGES_AUTH_REQUIRED',
            'CLI_TOKEN_INVALID',
            'ACCESS_KEY_INVALID',
            'ACCESS_KEY_REVOKED',
            'ACCESS_KEY_EXPIRED',
            'ACCESS_KEY_SESSION_STALE',
            'CONNECTION_ASSERTION_INVALID',
            'PAGES_USER_INACTIVE',
            'ACCESS_KEY_OWNER_INACTIVE',
            'PUBLIC_SITES_FORBIDDEN',
            'CONNECTION_IDENTITY_CONFLICT',
            'METHOD_NOT_ALLOWED',
            'API_STORE_UNAVAILABLE',
            'CONNECTION_KEYS_UNAVAILABLE',
            'PUBLIC_SITES_UNAVAILABLE',
          ],
          responses: {
            200: {
              description: 'Active sites discoverable by the authenticated user',
              content: {
                'application/json': { schema: { $ref: '#/components/schemas/PublicSitesResponse' } },
              },
            },
            400: { description: 'Invalid, repeated, or unknown query parameter, or unsupported legacy token header' },
            401: { description: 'Authentication is missing, invalid, expired, revoked, or stale' },
            403: { description: 'Active user directory access is forbidden for this credential' },
            405: { description: 'Only GET is supported' },
            409: { description: 'Cindy connection identity conflicts with an existing user' },
            500: { description: 'Pages API store binding is unavailable' },
            503: { description: 'Connection signing keys or the Public Sites directory are temporarily unavailable' },
          },
        },
      },
      '/.xd-pages/api/sites': {
        get: {
          summary: 'List sites visible to the authenticated actor; access keys require read:site or deploy:site',
          responses: {
            200: { description: 'Sites returned' },
            403: { description: 'Access key missing read:site or deploy:site scope' },
            401: { description: 'Authentication required' },
          },
        },
        post: {
          summary: 'Create a site',
          description:
            'User CLI tokens create personal sites by default. Supplying ownerType=team and teamId creates a team-owned ' +
            'site when the user is a team admin or publisher. Access keys cannot use this endpoint.',
          'x-error-codes': ['SITE_SLUG_CONFLICT', 'HOSTNAME_CLAIM_CONFLICT', 'SITE_CREATE_UNAVAILABLE'],
          responses: {
            201: { description: 'Site created' },
            403: { description: 'Team publisher role required or access key forbidden' },
            404: { description: 'Team not found' },
            409: { description: 'Site slug conflict' },
            503: { description: 'Site creation or legacy resource cleanup is temporarily unavailable' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}': {
        get: {
          summary: 'Get a site; access keys require read:site or deploy:site',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Site returned' },
            403: { description: 'Access key missing read:site or deploy:site scope' },
            404: { description: 'Site not found' },
          },
        },
        patch: {
          summary: 'Update site visibility as a site publisher/admin and invalidate sessions by policyVersion',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteUpdateRequest' },
              },
            },
          },
          'x-error-codes': [
            'SITE_VISIBILITY_INVALID',
            'SITE_EXPOSURE_ADMIN_REQUIRED',
            'SITE_POLICY_FORBIDDEN',
            'SITE_POLICY_CONFLICT',
            'ROUTE_POLICY_REPAIR_REQUIRED',
          ],
          responses: {
            200: { description: 'Site policy updated' },
            400: { description: 'Invalid visibility' },
            403: { description: 'Actor cannot manage this site' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
        delete: {
          summary: 'Soft-delete a manageable site and hold its hostname briefly before reuse',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          'x-error-codes': [
            'SITE_POLICY_FORBIDDEN',
            'SITE_POLICY_CONFLICT',
            'SITE_NOT_FOUND',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'ROUTE_POLICY_REPAIR_REQUIRED',
          ],
          responses: {
            200: { description: 'Site deleted' },
            403: { description: 'Actor cannot manage this site' },
            404: { description: 'Site not found' },
            409: { description: 'Site changed concurrently' },
            503: { description: 'Route snapshot write or recovery failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/metadata': {
        patch: {
          summary: 'Update a site display name or canonical URL slug',
          description:
            'Requires site management permission and deploy:site scope for access keys. Slug changes preserve the site ' +
            'identity and deployed version; the previous URL stops resolving and is released after a safety hold.',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteMetadataUpdateRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SITE_METADATA_INVALID',
            'SITE_TITLE_INVALID',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_SLUG_CONFLICT',
            'SITE_METADATA_CONFLICT',
            'SITE_NOT_FOUND',
            'SITE_METADATA_MUTATIONS_DISABLED',
            'SITE_METADATA_UPDATE_FAILED',
          ],
          responses: {
            200: {
              description: 'Site metadata saved; routingStatus may be ready or pending',
              content: {
                'application/json': { schema: { $ref: '#/components/schemas/SiteMetadataUpdateResponse' } },
              },
            },
            202: {
              description: 'Site metadata saved while route snapshots are still being reconciled',
              content: {
                'application/json': { schema: { $ref: '#/components/schemas/SiteMetadataPendingResponse' } },
              },
            },
            400: { description: 'Invalid JSON, metadata, title, or slug' },
            404: { description: 'Site not found or not manageable by this actor' },
            409: { description: 'Slug or concurrent metadata conflict' },
            500: { description: 'Site metadata update failed' },
            503: { description: 'Metadata mutations are disabled' },
          },
        },
      },
      '/.xd-pages/api/console/admin/sites/{id}/exposure': {
        patch: {
          summary: 'Update a site network exposure as a platform admin',
          description:
            'Admin-only Console BFF operation. exposure is independent from legacy visibility: ' +
            'public changes network reachability, ' +
            'while visibility continues to select anonymous, org, ACL, owner, or disabled access.',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/AdminSiteExposureRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SITE_NOT_FOUND',
            'PLATFORM_ADMIN_REQUIRED',
            'SITE_EXPOSURE_INVALID',
            'SITE_EXPOSURE_REASON_REQUIRED',
            'SITE_EXPOSURE_REASON_INVALID',
            'SITE_EXPOSURE_AUDIT_REQUIRED',
            'SITE_PUBLIC_ROUTE_INACTIVE',
            'SITE_POLICY_CONFLICT',
            'SITE_PUBLIC_OFFICE_NET_REMOVE_FAILED',
            'SITE_PUBLIC_OFFICE_NET_VERIFY_FAILED',
            'ROUTE_POLICY_REPAIR_REQUIRED',
            'SITE_EXPOSURE_UPDATE_FAILED',
          ],
          responses: {
            200: {
              description: 'Site exposure updated and effective in the route snapshot. auditStatus is confirmed or unconfirmed.',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AdminSiteExposureUpdateResponse' },
                },
              },
            },
            400: { description: 'Invalid exposure or missing reason' },
            403: { description: 'Platform admin required' },
            404: { description: 'Site not found' },
            409: { description: 'Site policy changed while the operation was being applied' },
            503: { description: 'Worker binding, route snapshot, or policy update failed' },
          },
        },
      },
      '/.xd-pages/api/console/admin/sites/{id}/access': {
        get: {
          summary: 'Read a site access policy as a platform admin',
          description:
            'Admin-only Console BFF operation. exposureReason is present only for the currently ' +
            'effective public exposure policy.',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: {
              description: 'Site access policy',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AdminSiteAccessResponse' },
                },
              },
            },
            403: { description: 'Platform admin required' },
            404: { description: 'Site not found' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/transfer': {
        post: {
          summary: 'Transfer a site asset to a personal or team owner',
          description:
            'Requires the current personal owner or an admin of the source team. Transfers to a team also require ' +
            'publisher/admin membership on the target team. Transfers to a personal owner remain limited to the ' +
            'authenticated actor. Team access tokens cannot change ownership, and the target must differ from the current owner.',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteTransferRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SITE_TRANSFER_INVALID',
            'SITE_VISIBILITY_INVALID',
            'SITE_POLICY_CONFLICT',
            'SITE_TRANSFER_FORBIDDEN',
            'TEAM_REQUIRED',
            'TEAM_NOT_FOUND',
            'SITE_NOT_FOUND',
            'SITE_TRANSFER_UNSUPPORTED',
            'ROUTE_POLICY_REPAIR_REQUIRED',
          ],
          responses: {
            200: { description: 'Site owner transferred' },
            400: { description: 'Invalid transfer request' },
            403: { description: 'Actor cannot transfer this site or target owner is not allowed' },
            404: { description: 'Site or team not found' },
            409: { description: 'Site changed concurrently' },
            503: { description: 'Site transfer store or route policy repair unavailable' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/acl': {
        get: {
          summary: 'List site ACL entries for a user or deploy-capable access key',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          'x-error-codes': ['SITE_POLICY_FORBIDDEN'],
          responses: {
            200: { description: 'ACL entries returned' },
            403: { description: 'Access key cannot manage the target site' },
            404: { description: 'Site not found' },
          },
        },
        put: {
          summary: 'Replace site ACL entries using allow-only OR semantics',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries replaced' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Actor cannot manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/acl/entries': {
        post: {
          summary: 'Grant additional site ACL entries using allow-only OR semantics',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries granted' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Actor cannot manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
        delete: {
          summary: 'Revoke site ACL entries incrementally',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries revoked' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Actor cannot manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{site}/secrets': {
        get: {
          summary: 'List site-level runtime secret metadata without secret values',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          'x-error-codes': [
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_UNSUPPORTED',
          ],
          responses: {
            200: {
              description: 'Enabled secret names, revisions, and update times returned without values',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/SiteSecretsResponse' },
                },
              },
            },
            403: { description: 'Actor cannot manage runtime secrets for this site' },
            404: { description: 'Site not found' },
            503: { description: 'Runtime secret metadata store unavailable' },
          },
        },
        put: {
          summary: 'Set a site-level runtime secret and sync the active Worker when present',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteSecretPutRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SECRET_NAME_INVALID',
            'SECRET_VALUE_INVALID',
            'SECRET_VALUE_TOO_LARGE',
            'RUNTIME_BINDING_NAME_CONFLICT',
            'RUNTIME_BINDINGS_LIMIT_EXCEEDED',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'SECRET_ACTIVE_WORKER_SYNC_FAILED',
          ],
          responses: {
            200: { description: 'Secret metadata returned without value' },
            400: { description: 'Invalid secret request or runtime binding name conflict' },
            403: { description: 'Actor cannot manage runtime secrets for this site' },
            404: { description: 'Site not found' },
            409: { description: 'Runtime secret changed while updating' },
            413: { description: 'Secret value or runtime binding quota exceeded' },
            502: { description: 'Active Worker secret sync failed after store update' },
            503: { description: 'Secret store or audit store unavailable' },
          },
        },
        delete: {
          summary: 'Disable a site-level runtime secret and sync the active Worker when present',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteSecretDeleteRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SECRET_NAME_INVALID',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'SECRET_ACTIVE_WORKER_SYNC_FAILED',
          ],
          responses: {
            200: { description: 'Secret deletion metadata returned without value' },
            400: { description: 'Invalid secret request' },
            403: { description: 'Actor cannot manage runtime secrets for this site' },
            404: { description: 'Site not found' },
            409: { description: 'Runtime secret changed while deleting' },
            502: { description: 'Active Worker secret sync failed after store update' },
            503: { description: 'Secret store or audit store unavailable' },
          },
        },
      },
      '/.xd-pages/api/sites/{site}/vars': {
        get: {
          summary: 'List non-sensitive site-level runtime vars',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          'x-error-codes': [
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_UNSUPPORTED',
          ],
          responses: {
            200: {
              description: 'Enabled runtime vars returned with values and metadata',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/SiteVarsResponse' },
                },
              },
            },
            403: { description: 'Actor cannot manage runtime config for this site' },
            404: { description: 'Site not found' },
            503: { description: 'Runtime config store unavailable' },
          },
        },
        put: {
          summary: 'Set one non-sensitive site-level runtime var and sync the active Worker when present',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteVarPutRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'RUNTIME_VAR_INVALID',
            'RUNTIME_BINDING_NAME_RESERVED',
            'RUNTIME_VARS_LIMIT_EXCEEDED',
            'RUNTIME_BINDING_NAME_CONFLICT',
            'RUNTIME_BINDINGS_LIMIT_EXCEEDED',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'RUNTIME_VAR_ACTIVE_WORKER_SYNC_FAILED',
          ],
          responses: {
            200: { description: 'Runtime var mutation metadata returned without the plain-text value' },
            400: { description: 'Invalid runtime var request or binding name conflict' },
            403: { description: 'Actor cannot manage runtime config for this site' },
            404: { description: 'Site not found' },
            409: { description: 'Runtime config changed while updating or synchronizing' },
            413: { description: 'Runtime var or shared binding quota exceeded' },
            502: { description: 'Active Worker runtime var sync failed after store update' },
            503: { description: 'Runtime config store unavailable' },
          },
        },
        delete: {
          summary: 'Delete one non-sensitive site-level runtime var and sync the active Worker when present',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteVarDeleteRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'RUNTIME_VAR_INVALID',
            'RUNTIME_BINDING_NAME_RESERVED',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'RUNTIME_VAR_ACTIVE_WORKER_SYNC_FAILED',
          ],
          responses: {
            200: { description: 'Runtime var deletion metadata returned without the plain-text value' },
            400: { description: 'Invalid runtime var request' },
            403: { description: 'Actor cannot manage runtime config for this site' },
            404: { description: 'Site not found' },
            409: { description: 'Runtime config changed while deleting or synchronizing' },
            502: { description: 'Active Worker runtime var sync failed after store update' },
            503: { description: 'Runtime config store unavailable' },
          },
        },
      },
      '/.xd-pages/api/access-keys': {
        get: {
          summary: 'List access keys',
          responses: {
            200: { description: 'Access keys returned without plaintext or hash' },
          },
        },
        post: {
          summary: 'Create a personal access key, optionally scoped to one site',
          'x-error-codes': [
            'ACCESS_KEY_CREATE_FORBIDDEN',
            'ACCESS_KEY_EXPIRY_INVALID',
            'ACCESS_KEY_EXPIRY_TOO_LONG',
            'ACCESS_KEY_NAME_INVALID',
            'ACCESS_KEY_SCOPE_INVALID',
            'ACCESS_KEY_SITE_REQUIRED',
            'ACCESS_KEY_SITE_FORBIDDEN',
            'SITE_NOT_FOUND',
          ],
          responses: {
            201: { description: 'Access key created; plaintext returned once' },
            403: { description: 'Actor cannot create an access key for the requested owner or site scope' },
          },
        },
      },
      '/.xd-pages/api/access-keys/{id}': {
        delete: {
          summary: 'Revoke an access key',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Access key revoked' },
            404: { description: 'Access key not found' },
          },
        },
      },
      '/.xd-pages/api/access-keys/current': {
        delete: {
          summary: 'Revoke the current CLI access key',
          description:
            'Revokes the cli_login access key used to authenticate this request. Non-CLI credentials receive 403; ' +
            'missing, invalid, or legacy tokens are rejected by authentication with 401.',
          responses: {
            200: { description: 'Current CLI access key revocation handled idempotently' },
            401: { description: 'Missing, invalid, or legacy credential' },
            403: { description: 'Credential is not a CLI credential' },
          },
        },
      },
      '/.xd-pages/api/auth/whoami': {
        get: {
          summary: 'Return the authenticated actor for CLI token or access key validation',
          responses: {
            200: {
              description: 'Authenticated actor returned without token plaintext or hashes',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/WhoamiResponse' },
                },
              },
            },
            401: { description: 'Authentication required or invalid' },
            403: { description: 'Authenticated user is not active' },
          },
        },
      },
      '/.xd-pages/api/teams': {
        get: {
          summary: 'List teams for the authenticated CLI user or personal access key owner',
          description:
            'Used by `xd-cell teams` to discover team ids for `xd-cell deploy --team <teamId>`. ' +
            'Requires a user CLI token or a personal access key with deploy:site/read:site. Team access keys cannot ' +
            'list user team memberships.',
          responses: {
            200: {
              description: 'Teams returned',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/TeamsResponse' },
                },
              },
            },
            401: { description: 'Authentication required or invalid' },
            403: { description: 'A user CLI token or personal access key is required' },
          },
        },
      },
      '/.xd-pages/api/deployments': {
        post: {
          summary: 'Create a deployment from a CLI-managed upload payload',
          description:
            'CLI-managed multipart upload. Personal/team access keys with deploy:site may create a new site ' +
            'during this deployment; tokens with a site scope can only deploy their bound site. User CLI tokens ' +
            'or personal access tokens may include teamId to deploy as a team publisher/admin. When the target ' +
            'slug already belongs to a personal site owned by the actor, or a team site where the actor is an admin, ' +
            'a different teamId requests an ownership transfer that is ' +
            'committed atomically with final route activation. A controlled integration may explicitly include title ' +
            'in the JSON metadata part; ' +
            'only an explicitly present title is applied, after the idempotency claim and before provider upload.',
          parameters: [{ name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'multipart/form-data': {
                schema: { $ref: '#/components/schemas/CliManagedDeploymentRequest' },
              },
            },
          },
          'x-error-codes': [
            'ASSET_MANIFEST_INVALID',
            'ASSET_FILES_REQUIRED',
            'CLI_UPLOAD_PROTOCOL_REQUIRED',
            'CONTENT_HASH_MISMATCH',
            'PUBLISH_PLAN_INVALID',
            'PUBLISH_PLAN_VERSION_UNSUPPORTED',
            'FALLBACK_REQUIRES_ASSETS',
            'INVALID_MULTIPART',
            'PAYLOAD_TOO_LARGE',
            'SITE_REQUIRED',
            'SITE_TITLE_INVALID',
            'SITE_METADATA_MUTATIONS_DISABLED',
            'SITE_METADATA_CONFLICT',
            'SITE_METADATA_UPDATE_FAILED',
            'SITE_NOT_FOUND',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_SLUG_CONFLICT',
            'SITE_VISIBILITY_INVALID',
            'HOSTNAME_CLAIM_CONFLICT',
            'SITE_CREATE_UNAVAILABLE',
            'TEAM_REQUIRED',
            'TEAM_NOT_FOUND',
            'TEAM_PUBLISHER_REQUIRED',
            'DEPLOY_FORBIDDEN',
            'DEPLOYMENT_PLATFORM_CONFIG_INVALID',
            'DEPLOYMENT_UPLOAD_FAILED',
            'DEPLOYMENT_VERIFY_FAILED',
            'DEPLOYMENT_STATE_WRITE_FAILED',
            'DEPLOYMENT_REQUEST_FAILED',
            'DEPLOYMENT_CAPACITY_EXHAUSTED',
            'SITE_POLICY_LOCKED',
            'SITE_POLICY_CONFLICT',
            'ROUTE_ACTIVATION_CONFLICT',
            'SITE_PUBLIC_OFFICE_NET_REMOVE_FAILED',
            'SITE_PUBLIC_OFFICE_NET_VERIFY_FAILED',
            'RUNTIME_VARS_INVALID',
            'RUNTIME_BINDING_NAME_CONFLICT',
            'RUNTIME_BINDINGS_LIMIT_EXCEEDED',
            'RUNTIME_VARS_REQUIRE_WORKER',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'IDEMPOTENCY_CONFLICT',
          ],
          responses: {
            201: deploymentTraceResponse('Deployment created; ownerTransfer is present when deployment changed site ownership'),
            400: deploymentTraceResponse('Invalid deployment request or title'),
            401: deploymentTraceResponse('Authentication required or invalid'),
            403: deploymentTraceResponse('Actor cannot deploy the requested site or exposure'),
            404: deploymentTraceResponse('Requested site or team was not found'),
            413: deploymentTraceResponse('Deployment payload too large for the current upload path'),
            500: deploymentTraceResponse('Deployment platform configuration, metadata update, or request processing failed'),
            502: deploymentTraceResponse('Deployment upload or verification failed'),
            503: deploymentTraceResponse(
              'Deployment capacity exhausted, site creation, metadata mutation, or route snapshot write failed'
            ),
            409: deploymentTraceResponse('Idempotency or site metadata conflict'),
          },
        },
      },
      '/.xd-pages/api/deployments/{id}': {
        get: {
          summary: 'Get deployment status; access keys require read:site',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Deployment returned' },
            403: { description: 'Access key missing read:site scope' },
            404: { description: 'Deployment not found' },
          },
        },
      },
      '/.xd-pages/api/versions/{id}/rollback': {
        post: {
          summary: 'Controlled rollback to a previous immutable version',
          description:
            'Controlled API. The public xd-cell CLI does not expose rollback commands; API auth and scopes still apply.',
          parameters: [
            { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string' } },
          ],
          requestBody: {
            required: false,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/RollbackRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SITE_NOT_FOUND',
            'VERSION_NOT_FOUND',
            'ROLLBACK_FORBIDDEN',
            'ROLLBACK_SITE_MISMATCH',
            'ROLLBACK_VERSION_UNAVAILABLE',
            'SITE_POLICY_LOCKED',
            'SITE_POLICY_CONFLICT',
            'ROLLBACK_ACTIVATION_FAILED',
            'SITE_PUBLIC_OFFICE_NET_REMOVE_FAILED',
            'SITE_PUBLIC_OFFICE_NET_VERIFY_FAILED',
            'ROUTE_ACTIVATION_CONFLICT',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'DEPLOYMENT_REQUEST_FAILED',
            'IDEMPOTENCY_CONFLICT',
          ],
          responses: {
            201: deploymentTraceResponse('Rollback deployment created'),
            400: deploymentTraceResponse('Invalid rollback request'),
            401: deploymentTraceResponse('Authentication required or invalid'),
            403: deploymentTraceResponse('Actor cannot rollback the requested site or exposure'),
            404: deploymentTraceResponse('Requested version or site was not found'),
            409: deploymentTraceResponse('Idempotency, policy, route activation, or version availability conflict'),
            500: deploymentTraceResponse('Rollback request processing failed'),
            503: deploymentTraceResponse('Rollback activation, state persistence, or route snapshot operation failed'),
          },
        },
      },
    },
  };
}

function deploymentTraceResponse(description) {
  return {
    description,
    headers: {
      'X-Deployment-Trace-Id': { $ref: '#/components/headers/DeploymentTraceId' },
    },
  };
}
