export function buildOpenApi(config) {
  return {
    openapi: '3.1.0',
    info: {
      title: 'XD Cell API',
      version: '2.0.0',
      description: 'Control plane API for XD Cell.',
    },
    servers: [{ url: config.apiBaseUrl }],
    security: [{ bearerAuth: [] }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'CLI token or access key',
        },
      },
      schemas: {
        ErrorResponse: {
          type: 'object',
          required: ['error'],
          properties: {
            error: {
              type: 'object',
              required: ['code', 'message'],
              properties: {
                code: { type: 'string' },
                message: { type: 'string' },
                action: { type: 'string' },
              },
            },
          },
        },
        CliManagedDeploymentRequest: {
          type: 'object',
          description:
            'Deployment upload payload generated by the XD Cell CLI. Use `xd-cell deploy <entry> <site>` or ' +
            '`xd-cell deploy --dry-run --json`; do not construct this payload by hand.',
          additionalProperties: true,
        },
        WhoamiResponse: {
          type: 'object',
          required: ['environment', 'actor'],
          properties: {
            environment: { type: 'string', enum: ['production', 'staging'] },
            actor: { $ref: '#/components/schemas/WhoamiActor' },
          },
        },
        WhoamiActor: {
          oneOf: [
            {
              type: 'object',
              required: ['type', 'credentialType', 'userId', 'email', 'name', 'scopes'],
              properties: {
                type: { type: 'string', const: 'user' },
                credentialType: { type: 'string', const: 'cli_token' },
                userId: { type: 'string' },
                email: { type: 'string', format: 'email' },
                name: { type: ['string', 'null'] },
                scopes: { type: 'array', items: { type: 'string' } },
              },
              additionalProperties: false,
            },
            {
              type: 'object',
              required: ['type', 'credentialType', 'accessKeyId', 'userId', 'email', 'name', 'siteId', 'scopes'],
              properties: {
                type: { type: 'string', const: 'access_key' },
                credentialType: { type: 'string', const: 'access_key' },
                accessKeyId: { type: 'string' },
                userId: { type: 'string' },
                email: { type: 'string', format: 'email' },
                name: { type: ['string', 'null'] },
                siteId: { type: ['string', 'null'] },
                scopes: { type: 'array', items: { type: 'string' } },
              },
              additionalProperties: false,
            },
          ],
        },
        DeploymentDecision: {
          type: 'object',
          required: ['deploymentShape', 'requestedFallback', 'resolvedFallback', 'routingMode'],
          properties: {
            deploymentShape: {
              type: 'string',
              enum: ['assets-only', 'worker-only', 'worker-with-assets'],
              description: 'Resolved platform execution shape. Returned for explanation; not a user input field.',
            },
            requestedFallback: {
              type: 'string',
              enum: ['auto', 'index', 'not-found', 'none', 'single-page-application', '404-page'],
            },
            resolvedFallback: { type: ['string', 'null'], enum: ['index', 'not-found', 'none', null] },
            routingMode: {
              type: 'string',
              enum: ['assets-only', 'worker-only', 'worker-first'],
            },
          },
        },
        RollbackRequest: {
          type: 'object',
          properties: {
            siteId: {
              type: 'string',
              description: 'Optional guardrail. If provided, the target version must belong to this site id.',
            },
            siteSlug: {
              type: 'string',
              description: 'Optional guardrail. If provided, the target version must belong to this site slug.',
            },
          },
        },
        SiteVisibility: {
          type: 'string',
          enum: ['internal', 'org', 'acl', 'owner', 'disabled'],
          description:
            'First release is protected by the router IP allowlist for every visibility. ' +
            'public is reserved for a future exposure model.',
        },
        SiteUpdateRequest: {
          type: 'object',
          required: ['visibility'],
          properties: {
            visibility: { $ref: '#/components/schemas/SiteVisibility' },
          },
        },
        SiteAclEntry: {
          type: 'object',
          required: ['subjectType', 'subjectValue'],
          properties: {
            subjectType: {
              type: 'string',
              enum: ['email', 'department'],
              description:
                'People are specified by email. Departments are specified by full department path and include subdepartments. ' +
                'Internal SSO user ids, account ids, employee numbers, and group subjects are not accepted as public ' +
                'ACL subjects.',
            },
            subjectValue: { type: 'string' },
            effect: {
              type: 'string',
              enum: ['allow'],
              default: 'allow',
              description: 'deny is not supported in the first release.',
            },
            accessRole: {
              type: 'string',
              enum: ['viewer'],
              default: 'viewer',
            },
          },
        },
        SiteAclReplaceRequest: {
          type: 'object',
          required: ['entries'],
          properties: {
            entries: {
              type: 'array',
              maxItems: 200,
              items: { $ref: '#/components/schemas/SiteAclEntry' },
            },
          },
        },
        SiteSecretPutRequest: {
          type: 'object',
          required: ['name', 'value'],
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              description: 'Worker binding name. Secret value is never returned by the API.',
            },
            value: {
              type: 'string',
              minLength: 1,
              description: 'Secret value. Do not log or persist this outside the secret store.',
            },
          },
        },
        SiteSecretDeleteRequest: {
          type: 'object',
          required: ['name'],
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              description: 'Worker binding name to disable for future deployments.',
            },
          },
        },
      },
    },
    paths: {
      '/.xd-pages/api/sites': {
        get: {
          summary: 'List sites visible to the authenticated actor; access keys require read:site',
          responses: {
            200: { description: 'Sites returned' },
            403: { description: 'Access key missing read:site scope' },
            401: { description: 'Authentication required' },
          },
        },
        post: {
          summary: 'Create a site',
          responses: {
            201: { description: 'Site created' },
            409: { description: 'Site slug conflict' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}': {
        get: {
          summary: 'Get a site; access keys require read:site',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Site returned' },
            403: { description: 'Access key missing read:site scope' },
            404: { description: 'Site not found' },
          },
        },
        patch: {
          summary: 'Update site visibility and invalidate existing site sessions by policyVersion',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteUpdateRequest' },
              },
            },
          },
          'x-error-codes': ['SITE_VISIBILITY_INVALID', 'SITE_POLICY_FORBIDDEN', 'ROUTE_SNAPSHOT_WRITE_FAILED'],
          responses: {
            200: { description: 'Site policy updated' },
            400: { description: 'Invalid visibility' },
            403: { description: 'Only the site owner can manage site policy' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
        delete: {
          summary: 'Soft-delete an owned site and hold its hostname briefly before reuse',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          'x-error-codes': ['SITE_POLICY_FORBIDDEN', 'SITE_NOT_FOUND'],
          responses: {
            200: { description: 'Site deleted' },
            403: { description: 'Only the site owner can delete the site' },
            404: { description: 'Site not found' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/acl': {
        get: {
          summary: 'List site ACL entries',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'ACL entries returned' },
            404: { description: 'Site not found' },
          },
        },
        put: {
          summary: 'Replace site ACL entries using allow-only OR semantics',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries replaced' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Only the site owner can manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{id}/acl/entries': {
        post: {
          summary: 'Grant additional site ACL entries using allow-only OR semantics',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries granted' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Only the site owner can manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
        delete: {
          summary: 'Revoke site ACL entries incrementally',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteAclReplaceRequest' },
              },
            },
          },
          'x-error-codes': [
            'ACL_ENTRIES_INVALID',
            'ACL_EFFECT_UNSUPPORTED',
            'ACL_ROLE_UNSUPPORTED',
            'ACL_SUBJECT_TYPE_UNSUPPORTED',
            'ACL_SUBJECT_VALUE_INVALID',
            'SITE_POLICY_FORBIDDEN',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
          ],
          responses: {
            200: { description: 'ACL entries revoked' },
            400: { description: 'Invalid ACL request' },
            403: { description: 'Only the site owner can manage site ACL' },
            404: { description: 'Site not found' },
            503: { description: 'Route snapshot write failed' },
          },
        },
      },
      '/.xd-pages/api/sites/{site}/secrets': {
        put: {
          summary: 'Set a site-level runtime secret and sync the active Worker when present',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteSecretPutRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SECRET_NAME_INVALID',
            'SECRET_VALUE_INVALID',
            'SECRET_VALUE_TOO_LARGE',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'SECRET_ACTIVE_WORKER_SYNC_FAILED',
          ],
          responses: {
            200: { description: 'Secret metadata returned without value' },
            400: { description: 'Invalid secret request' },
            403: { description: 'Actor cannot manage runtime secrets for this site' },
            404: { description: 'Site not found' },
            409: { description: 'Runtime secret changed while updating' },
            413: { description: 'Secret value too large' },
            502: { description: 'Active Worker secret sync failed after store update' },
            503: { description: 'Secret store or audit store unavailable' },
          },
        },
        delete: {
          summary: 'Disable a site-level runtime secret and sync the active Worker when present',
          parameters: [{ name: 'site', in: 'path', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/SiteSecretDeleteRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SECRET_NAME_INVALID',
            'SITE_NOT_FOUND',
            'DEPLOY_FORBIDDEN',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'SECRET_ACTIVE_WORKER_SYNC_FAILED',
          ],
          responses: {
            200: { description: 'Secret deletion metadata returned without value' },
            400: { description: 'Invalid secret request' },
            403: { description: 'Actor cannot manage runtime secrets for this site' },
            404: { description: 'Site not found' },
            409: { description: 'Runtime secret changed while deleting' },
            502: { description: 'Active Worker secret sync failed after store update' },
            503: { description: 'Secret store or audit store unavailable' },
          },
        },
      },
      '/.xd-pages/api/access-keys': {
        get: {
          summary: 'List access keys',
          responses: {
            200: { description: 'Access keys returned without plaintext or hash' },
          },
        },
        post: {
          summary: 'Create a site-scoped access key',
          'x-error-codes': [
            'ACCESS_KEY_CREATE_FORBIDDEN',
            'ACCESS_KEY_EXPIRY_INVALID',
            'ACCESS_KEY_EXPIRY_TOO_LONG',
            'ACCESS_KEY_NAME_INVALID',
            'ACCESS_KEY_SCOPE_INVALID',
            'ACCESS_KEY_SITE_REQUIRED',
            'ACCESS_KEY_SITE_FORBIDDEN',
            'SITE_NOT_FOUND',
          ],
          responses: {
            201: { description: 'Access key created; plaintext returned once' },
            403: { description: 'Only the site owner can create deploy-capable access keys' },
          },
        },
      },
      '/.xd-pages/api/access-keys/{id}': {
        delete: {
          summary: 'Revoke an access key',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Access key revoked' },
            404: { description: 'Access key not found' },
          },
        },
      },
      '/.xd-pages/api/auth/whoami': {
        get: {
          summary: 'Return the authenticated actor for CLI token or access key validation',
          responses: {
            200: {
              description: 'Authenticated actor returned without token plaintext or hashes',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/WhoamiResponse' },
                },
              },
            },
            401: { description: 'Authentication required or invalid' },
            403: { description: 'Authenticated user is not active' },
          },
        },
      },
      '/.xd-pages/api/deployments': {
        post: {
          summary: 'Create a deployment from a CLI-managed upload payload',
          description:
            'CLI-managed multipart upload. Owner-scoped access keys with deploy:site may create a new site ' +
            'during this deployment; site-scoped access keys can only deploy their bound site. Direct site ' +
            'creation remains outside the access-key API surface.',
          parameters: [{ name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string' } }],
          requestBody: {
            required: true,
            content: {
              'multipart/form-data': {
                schema: { $ref: '#/components/schemas/CliManagedDeploymentRequest' },
              },
            },
          },
          'x-error-codes': [
            'ASSET_MANIFEST_INVALID',
            'ASSET_FILES_REQUIRED',
            'CLI_UPLOAD_PROTOCOL_REQUIRED',
            'CONTENT_HASH_MISMATCH',
            'PUBLISH_PLAN_INVALID',
            'PUBLISH_PLAN_VERSION_UNSUPPORTED',
            'FALLBACK_REQUIRES_ASSETS',
            'INVALID_MULTIPART',
            'PAYLOAD_TOO_LARGE',
            'SITE_REQUIRED',
            'SITE_NOT_FOUND',
            'SITE_SLUG_INVALID',
            'SITE_SLUG_RESERVED',
            'SITE_SLUG_CONFLICT',
            'SITE_VISIBILITY_INVALID',
            'HOSTNAME_CLAIM_CONFLICT',
            'DEPLOY_FORBIDDEN',
            'DEPLOYMENT_PLATFORM_CONFIG_INVALID',
            'DEPLOYMENT_UPLOAD_FAILED',
            'DEPLOYMENT_VERIFY_FAILED',
            'DEPLOYMENT_STATE_WRITE_FAILED',
            'DEPLOYMENT_CAPACITY_EXHAUSTED',
            'RUNTIME_VARS_INVALID',
            'RUNTIME_BINDING_NAME_CONFLICT',
            'RUNTIME_BINDINGS_LIMIT_EXCEEDED',
            'RUNTIME_VARS_REQUIRE_WORKER',
            'RUNTIME_CONFIG_CHANGED',
            'RUNTIME_CONFIG_UNSUPPORTED',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'IDEMPOTENCY_CONFLICT',
          ],
          responses: {
            201: { description: 'Deployment created' },
            400: { description: 'Invalid deployment request' },
            413: { description: 'Deployment payload too large for the current upload path' },
            500: { description: 'Deployment platform configuration invalid' },
            502: { description: 'Deployment upload or verification failed' },
            503: { description: 'Deployment capacity exhausted or route snapshot write failed' },
            409: { description: 'Idempotency conflict' },
          },
        },
      },
      '/.xd-pages/api/deployments/{id}': {
        get: {
          summary: 'Get deployment status; access keys require read:site',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: 'Deployment returned' },
            403: { description: 'Access key missing read:site scope' },
            404: { description: 'Deployment not found' },
          },
        },
      },
      '/.xd-pages/api/versions/{id}/rollback': {
        post: {
          summary: 'Controlled rollback to a previous immutable version',
          description:
            'Controlled API. The public xd-cell CLI does not expose rollback commands; API auth and scopes still apply.',
          parameters: [
            { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string' } },
          ],
          requestBody: {
            required: false,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/RollbackRequest' },
              },
            },
          },
          'x-error-codes': [
            'INVALID_JSON',
            'SITE_NOT_FOUND',
            'VERSION_NOT_FOUND',
            'ROLLBACK_FORBIDDEN',
            'ROLLBACK_SITE_MISMATCH',
            'ROLLBACK_VERSION_UNAVAILABLE',
            'ROUTE_ACTIVATION_CONFLICT',
            'ROUTE_SNAPSHOT_WRITE_FAILED',
            'IDEMPOTENCY_CONFLICT',
          ],
          responses: {
            201: { description: 'Rollback deployment created' },
            409: { description: 'Idempotency conflict' },
          },
        },
      },
    },
  };
}
