const EVENT_DESCRIPTORS = [
  {
    type: 'site.deployed',
    label: '部署成功',
    description: '站点部署成功并激活后触发',
    requiredTemplateVariables: [
      'event.id',
      'event.type',
      'event.environment',
      'event.occurredAt',
      'site.id',
      'site.slug',
      'site.ownerType',
      'site.status',
    ],
    optionalTemplateVariables: [
      'actor.type',
      'actor.userId',
      'actor.email',
      'actor.name',
      'site.hostname',
      'site.ownerId',
      'site.visibility',
      'team.id',
      'team.name',
      'team.teamType',
      'deployment.id',
      'deployment.status',
      'deployment.source',
      'deployment.operation',
      'deployment.createdAt',
      'deployment.completedAt',
    ],
  },
  {
    type: 'site.failed',
    label: '部署失败',
    description: '站点部署或回滚进入失败终态时触发',
    requiredTemplateVariables: [
      'event.id',
      'event.type',
      'event.environment',
      'event.occurredAt',
      'site.id',
      'site.slug',
      'site.ownerType',
      'deployment.id',
      'deployment.status',
      'deployment.operation',
    ],
    optionalTemplateVariables: [
      'actor.type',
      'actor.userId',
      'actor.email',
      'actor.name',
      'site.hostname',
      'site.ownerId',
      'site.visibility',
      'site.status',
      'team.id',
      'team.name',
      'team.teamType',
      'deployment.source',
      'deployment.createdAt',
      'deployment.completedAt',
      'deployment.failureStage',
      'deployment.errorCode',
    ],
  },
  {
    type: 'site.disabled',
    label: '站点停用',
    description: '站点访问策略成功切换为 disabled 后触发',
    requiredTemplateVariables: [
      'event.id',
      'event.type',
      'event.environment',
      'event.occurredAt',
      'actor.type',
      'site.id',
      'site.slug',
      'site.ownerType',
      'site.visibility',
      'change.field',
      'change.previousValue',
      'change.currentValue',
    ],
    optionalTemplateVariables: [
      'actor.userId',
      'actor.email',
      'actor.name',
      'site.hostname',
      'site.ownerId',
      'site.status',
      'team.id',
      'team.name',
      'team.teamType',
    ],
  },
  {
    type: 'site.deleted',
    label: '站点删除',
    description: '站点删除流程成功完成后触发',
    requiredTemplateVariables: [
      'event.id',
      'event.type',
      'event.environment',
      'event.occurredAt',
      'actor.type',
      'site.id',
      'site.slug',
      'site.ownerType',
      'site.status',
    ],
    optionalTemplateVariables: [
      'actor.userId',
      'actor.email',
      'actor.name',
      'site.hostname',
      'site.ownerId',
      'site.visibility',
      'team.id',
      'team.name',
      'team.teamType',
    ],
  },
];

export const SUPPORTED_WEBHOOK_EVENTS = new Set(EVENT_DESCRIPTORS.map(({ type }) => type));

export function getWebhookEventCatalog() {
  return EVENT_DESCRIPTORS.map((event) => ({
    ...event,
    requiredTemplateVariables: [...event.requiredTemplateVariables],
    optionalTemplateVariables: [...event.optionalTemplateVariables],
    templateVariables: [...event.requiredTemplateVariables, ...event.optionalTemplateVariables],
  }));
}

export function getWebhookTemplateVariablePaths() {
  return new Set(getWebhookEventCatalog().flatMap((event) => event.templateVariables));
}
