name = "xdads-302"
main = "index.js"
compatibility_date = "2025-05-01"
account_id = "__CLOUDFLARE_ACCOUNT_ID__"

[[routes]]
pattern = "*-page.xd-ads.com/*"
zone_id = "__OLD_ZONE_ID__"

[[routes]]
pattern = "pages-api.xd-ads.com/*"
zone_id = "__OLD_ZONE_ID__"
