name = "xdads-302"
main = "index.js"
compatibility_date = "2025-05-01"
account_id = "<CLOUDFLARE_ACCOUNT_ID>"

[[routes]]
pattern = "*-page.xd-ads.com/*"
zone_id = "<OLD_ZONE_ID>"

[[routes]]
pattern = "pages-api.xd-ads.com/*"
zone_id = "<OLD_ZONE_ID>"
