apiVersion: v1
kind: ServiceAccount
metadata:
  name: pages-manager-ack-preview-deployer
  namespace: pages-manager-preview
  labels:
    app.kubernetes.io/name: pages-manager-ack-preview-deployer
    app.kubernetes.io/part-of: pages-manager
    pages.xd.team/environment: ack-preview
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pages-manager-ack-preview-deployer
  namespace: pages-manager-preview
  labels:
    app.kubernetes.io/name: pages-manager-ack-preview-deployer
    app.kubernetes.io/part-of: pages-manager
    pages.xd.team/environment: ack-preview
rules:
  - apiGroups: ['']
    resources:
      - configmaps
      - persistentvolumeclaims
      - serviceaccounts
      - services
    verbs: [get, list, watch, create, patch, update]
  - apiGroups: ['']
    resources:
      - pods
    verbs: [get, list, watch]
  - apiGroups: ['']
    resources:
      - pods/exec
    verbs: [create]
  - apiGroups: [apps]
    resources:
      - deployments
    verbs: [get, list, watch, create, patch, update]
  - apiGroups: [apps]
    resources:
      - replicasets
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources:
      - ingresses
    verbs: [get, list, watch, create, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pages-manager-ack-preview-deployer
  namespace: pages-manager-preview
  labels:
    app.kubernetes.io/name: pages-manager-ack-preview-deployer
    app.kubernetes.io/part-of: pages-manager
    pages.xd.team/environment: ack-preview
subjects:
  - kind: ServiceAccount
    name: pages-manager-ack-preview-deployer
    namespace: pages-manager-preview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pages-manager-ack-preview-deployer
