apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pages-gateway-data
  namespace: pages-system
  labels:
    app.kubernetes.io/name: pages-gateway-data
    app.kubernetes.io/part-of: pages-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
