apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pages-system
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - gateway-pvc.yaml
  - gateway.yaml
  - worker.yaml
  - slack-agent.yaml
  - slack-notifier.yaml
