apiVersion: v1
kind: ServiceAccount
metadata:
  name: pages-control-plane
  namespace: pages-system
  labels:
    app.kubernetes.io/name: pages-control-plane
    app.kubernetes.io/part-of: pages-manager
